/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package multipleloginarraylist;

import java.awt.event.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class BankTransfer extends javax.swing.JFrame {

    /**
     * Creates new form BankTransfer
     */
    public BankTransfer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cashpaybtn1 = new javax.swing.JButton();
        cashpaybtn2 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        transfertxt2 = new javax.swing.JTextField();
        transfertxt3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashpaybtn1.setBackground(new java.awt.Color(89, 0, 0));
        cashpaybtn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cashpaybtn1.setForeground(new java.awt.Color(255, 255, 255));
        cashpaybtn1.setText("Pay Now");
        cashpaybtn1.setRequestFocusEnabled(false);
        cashpaybtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashpaybtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(cashpaybtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, 40));

        cashpaybtn2.setBackground(new java.awt.Color(89, 0, 0));
        cashpaybtn2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cashpaybtn2.setForeground(new java.awt.Color(255, 255, 255));
        cashpaybtn2.setText("Back");
        cashpaybtn2.setRequestFocusEnabled(false);
        cashpaybtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashpaybtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(cashpaybtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 130, 40));

        jPanel36.setBackground(new java.awt.Color(118, 4, 4));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 153, 51));
        jLabel49.setText("Bank Transfer Payment");

        jLabel65.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("*Account Number:");

        jLabel63.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("*Account Name:");

        jLabel64.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("*Bank Name:");

        transfertxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transfertxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                transfertxt2KeyPressed(evt);
            }
        });

        transfertxt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transfertxt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                transfertxt3KeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BANK", " ", "BPI", "BDO", "METRO BANK", "LANDBANK", "PNB" }));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel36Layout.createSequentialGroup()
                                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(transfertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel36Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(transfertxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addGap(37, 37, 37))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel49)
                .addGap(57, 57, 57)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfertxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashpaybtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashpaybtn1ActionPerformed
        if (jComboBox1.getSelectedIndex()==0 || jComboBox1.getSelectedIndex()==1 || transfertxt2.getText().equals("") || transfertxt3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ENTER ALL FIELDS!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Payment Successful!");
            jComboBox1.setSelectedIndex(0);
            transfertxt2.setText("");
            transfertxt3.setText("");
        }
    }//GEN-LAST:event_cashpaybtn1ActionPerformed

    private void cashpaybtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashpaybtn2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cashpaybtn2ActionPerformed

    private void transfertxt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transfertxt2KeyPressed
        String accnum = transfertxt2.getText();
        int accnum_length = accnum.length();
        char accnum2 = evt.getKeyChar();

        if (Character.isDigit(accnum2)) {

            if (accnum_length < 16) {
                transfertxt2.setEditable(true);
            } else {
                transfertxt2.setEditable(false);
            }
        } else {
            if (Character.isISOControl(accnum2)) {
                transfertxt2.setEditable(true);
            } else {
                transfertxt2.setEditable(false);
            }
        }
    }//GEN-LAST:event_transfertxt2KeyPressed

    private void transfertxt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transfertxt3KeyPressed
        String accname = transfertxt3.getText();
        int accname_length = accname.length();
        char accname2 = evt.getKeyChar();

        if (Character.isLetter(accname2)) {

            if (accname_length < 30) {
                transfertxt3.setEditable(true);
            } else {
                transfertxt3.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(accname2) || Character.isISOControl(accname2)) {
                transfertxt3.setEditable(true);
            } else {
                transfertxt3.setEditable(false);
            }
        }
    }//GEN-LAST:event_transfertxt3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BankTransfer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashpaybtn1;
    private javax.swing.JButton cashpaybtn2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JTextField transfertxt2;
    private javax.swing.JTextField transfertxt3;
    // End of variables declaration//GEN-END:variables
}
