/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package multipleloginarraylist;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Billing extends javax.swing.JFrame {
    
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        cardpaybtn2 = new javax.swing.JButton();
        cardpaybtn1 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cardpaytxt5 = new javax.swing.JTextField();
        cardpaytxt3 = new javax.swing.JTextField();
        cardpaytxt2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 153, 51));
        jLabel49.setText("Credit / Debit Card Payment");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, -1));

        cardpaybtn2.setBackground(new java.awt.Color(89, 0, 0));
        cardpaybtn2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cardpaybtn2.setForeground(new java.awt.Color(255, 255, 255));
        cardpaybtn2.setText("Back");
        cardpaybtn2.setRequestFocusEnabled(false);
        cardpaybtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardpaybtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(cardpaybtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 130, 40));

        cardpaybtn1.setBackground(new java.awt.Color(89, 0, 0));
        cardpaybtn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cardpaybtn1.setForeground(new java.awt.Color(255, 255, 255));
        cardpaybtn1.setText("Pay Now");
        cardpaybtn1.setRequestFocusEnabled(false);
        cardpaybtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardpaybtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(cardpaybtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 130, 40));

        jPanel36.setBackground(new java.awt.Color(118, 4, 4));
        jPanel36.setForeground(new java.awt.Color(255, 255, 255));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Card Details");
        jPanel36.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 64, 172, -1));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("*Cardholder Name:");
        jPanel36.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("*Card Number:");
        jPanel36.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, -1));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("*Expiry Date:");
        jPanel36.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("*Card security code:");
        jPanel36.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));

        cardpaytxt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardpaytxt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardpaytxt5KeyPressed(evt);
            }
        });
        jPanel36.add(cardpaytxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 270, 30));

        cardpaytxt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardpaytxt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardpaytxt3KeyPressed(evt);
            }
        });
        jPanel36.add(cardpaytxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 270, 30));

        cardpaytxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardpaytxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardpaytxt2KeyPressed(evt);
            }
        });
        jPanel36.add(cardpaytxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", " ", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel36.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel36.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 80, 30));

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardpaytxt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardpaytxt3KeyPressed
        String cardnum = cardpaytxt3.getText();
        int cardnum_length = cardnum.length();
        char card = evt.getKeyChar();

        if (Character.isDigit(card)) {
            if (cardnum_length < 16) {
                cardpaytxt3.setEditable(true);
            } else {
                cardpaytxt3.setEditable(false);
            }
        } else {
            if (Character.isISOControl(card)) {
                cardpaytxt3.setEditable(true);
            } else {
                cardpaytxt3.setEditable(false);
            }
        }
    }//GEN-LAST:event_cardpaytxt3KeyPressed

    private void cardpaytxt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardpaytxt5KeyPressed
        String cardcode = cardpaytxt5.getText();
        int cardcode_length = cardcode.length();
        char code = evt.getKeyChar();

        if (Character.isDigit(code)) {
            if (cardcode_length < 3) {
                cardpaytxt5.setEditable(true);
            } else {
                cardpaytxt5.setEditable(false);
            }
        } else {
            if (Character.isISOControl(code)) {
                cardpaytxt5.setEditable(true);
            } else {
                cardpaytxt5.setEditable(false);
            }
        }
    }//GEN-LAST:event_cardpaytxt5KeyPressed

    private void cardpaybtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardpaybtn2ActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_cardpaybtn2ActionPerformed

    private void cardpaybtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardpaybtn1ActionPerformed
        if (cardpaytxt2.getText().equals("") || cardpaytxt3.getText().equals("") || cardpaytxt5.getText().equals("")
                || jComboBox2.getSelectedItem().equals("Month") || jComboBox1.getSelectedItem().equals("Year") 
                || jComboBox2.getSelectedIndex()==1 || jComboBox1.getSelectedIndex()==1)
                JOptionPane.showMessageDialog(null, "ENTER ALL FIELDS!");
        else{
            JOptionPane.showMessageDialog(null, "Payment Successful!");
            cardpaytxt2.setText("");
            cardpaytxt3.setText("");
            cardpaytxt5.setText("");
            jComboBox2.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
        }       
    }//GEN-LAST:event_cardpaybtn1ActionPerformed

    private void cardpaytxt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardpaytxt2KeyPressed
        String cardname = cardpaytxt2.getText();
        int cardname_length = cardname.length();
        char cardname2 = evt.getKeyChar();

        if (Character.isLetter(cardname2)) {

            if (cardname_length < 30) {
                cardpaytxt2.setEditable(true);
            } else {
                cardpaytxt2.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(cardname2) || Character.isISOControl(cardname2)) {
                cardpaytxt2.setEditable(true);
            } else {
                cardpaytxt2.setEditable(false);
            }
        }
    }//GEN-LAST:event_cardpaytxt2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Billing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardpaybtn1;
    private javax.swing.JButton cardpaybtn2;
    private javax.swing.JTextField cardpaytxt2;
    private javax.swing.JTextField cardpaytxt3;
    private javax.swing.JTextField cardpaytxt5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel36;
    // End of variables declaration//GEN-END:variables
}
