/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package multipleloginarraylist;
import java.awt.event.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class CashPay extends javax.swing.JFrame {

    /**
     * Creates new form CashPay
     */
    public CashPay() {
        initComponents();
        this.setLocationRelativeTo(null);
        cashpaytxt3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cashpaybtn1 = new javax.swing.JButton();
        cashpaybtn2 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        cashpaytxt1 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        cashpaytxt2 = new javax.swing.JTextField();
        cashpaytxt3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashpaybtn1.setBackground(new java.awt.Color(89, 0, 0));
        cashpaybtn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cashpaybtn1.setForeground(new java.awt.Color(255, 255, 255));
        cashpaybtn1.setText("Pay Now");
        cashpaybtn1.setRequestFocusEnabled(false);
        cashpaybtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashpaybtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(cashpaybtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, 40));

        cashpaybtn2.setBackground(new java.awt.Color(89, 0, 0));
        cashpaybtn2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cashpaybtn2.setForeground(new java.awt.Color(255, 255, 255));
        cashpaybtn2.setText("Back");
        cashpaybtn2.setRequestFocusEnabled(false);
        cashpaybtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashpaybtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(cashpaybtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, 40));

        jPanel36.setBackground(new java.awt.Color(118, 4, 4));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 153, 0));
        jLabel49.setText("Cash Payment");

        cashpaytxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cashpaytxt1KeyPressed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("*Enter Amount:");

        jLabel68.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("*Cash:");

        jLabel67.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Change:");

        cashpaytxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cashpaytxt2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel36Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jLabel66)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashpaytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel36Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashpaytxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel36Layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cashpaytxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel49)
                .addGap(42, 42, 42)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashpaytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashpaytxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashpaytxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashpaybtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashpaybtn1ActionPerformed
        
        String cashpayamountText = cashpaytxt1.getText();
        String cashpayinText = cashpaytxt2.getText();

        if (cashpayamountText.isEmpty() || cashpayinText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ENTER ALL REQUIRED FIELDS!");
        } else {
            try {
                int cashpayamount = Integer.parseInt(cashpayamountText);
                int cashpayin = Integer.parseInt(cashpayinText);
                int change = cashpayin - cashpayamount;
                String newchange = Integer.toString(change);

                if (cashpayin < cashpayamount){
                    JOptionPane.showMessageDialog(null, "Money is insufficient");
                }
                else if(cashpayamount < 500){
                    JOptionPane.showMessageDialog(null, "Total amount must be valid");
                }
                else {
                    JOptionPane.showMessageDialog(null, "PAYMENT SUCCESSFUL!");
                    String totalearnings = Dashboardd.totalearnslbl.getText();
                    String amount = cashpayamountText;
                    int totalearningss = Integer.parseInt(totalearnings);
                    int amountt = Integer.parseInt(amount);
                    int totall = totalearningss + amountt;
                    String totalll = Integer.toString(totall);
                    Dashboardd.totalearnslbl.setText(totalll);
                    MultipleLogin.totalearnings.add(totalll);
                    cashpaytxt3.setText(newchange);
                    cashpaytxt1.setText("");
                    cashpaytxt2.setText("");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid numbers.");
    }
}
    }//GEN-LAST:event_cashpaybtn1ActionPerformed

    private void cashpaybtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashpaybtn2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cashpaybtn2ActionPerformed

    private void cashpaytxt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashpaytxt2KeyPressed
        String cash1 = cashpaytxt2.getText();
        int cash1_length = cash1.length();
        char b1 = evt.getKeyChar();

        if (Character.isDigit(b1)) {

            if (cash1_length < 20) {
                cashpaytxt2.setEditable(true);
            } else {
                cashpaytxt2.setEditable(false);
            }
        } else {
            if (Character.isISOControl(b1)) {
                cashpaytxt2.setEditable(true);
            } else {
                cashpaytxt2.setEditable(false);
            }
        }
    }//GEN-LAST:event_cashpaytxt2KeyPressed

    private void cashpaytxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashpaytxt1KeyPressed
        String amount1 = cashpaytxt1.getText();
        int amount1_length = amount1.length();
        char b1 = evt.getKeyChar();

        if (Character.isDigit(b1)) {

            if (amount1_length < 20) {
                cashpaytxt1.setEditable(true);
            } else {
                cashpaytxt1.setEditable(false);
            }
        } else {
            if (Character.isISOControl(b1)) {
                cashpaytxt1.setEditable(true);
            } else {
                cashpaytxt1.setEditable(false);
            }
        }
    }//GEN-LAST:event_cashpaytxt1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new CashPay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashpaybtn1;
    private javax.swing.JButton cashpaybtn2;
    public static javax.swing.JTextField cashpaytxt1;
    public static javax.swing.JTextField cashpaytxt2;
    private javax.swing.JTextField cashpaytxt3;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel36;
    // End of variables declaration//GEN-END:variables
}
