/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package multipleloginarraylist;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Loginn extends javax.swing.JFrame {
    public int attempt = 3; 
    public Statement st;
    public Connection cn;
    
    Dashboardd dboardd = new Dashboardd();
    
    Date logindate = new Date();
    SimpleDateFormat dat = new SimpleDateFormat("MMM / dd / yy");
    SimpleDateFormat dat1 = new SimpleDateFormat("hh:mm a");
    String dat2 = dat.format(logindate);

    /**
     * Creates new form Loginn
     */
    public Loginn() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            st=cn.createStatement();
            JOptionPane.showMessageDialog(null,"Connected");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
        
        logindatelbl.setText(dat2);
        
        prog();
    }
    Timer logintime;
    SimpleDateFormat logintimest;
    
    public void prog(){
        logintime = new Timer (1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                String logtime = dat1.format(dt);
                logintimelbl.setText(logtime);
            }
            }); 
        logintime.start();
    }
    public class prog implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent evt)
        {
            int n = Loginn_pb1.getValue();
            if(n<100)
            {
                n++;
                Loginn_pb1.setValue(n); 
                
            }
            else{
                JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                setVisible(false);
                dboardd.setVisible(true);
                tmr.stop(); 
            }
        }
       }
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        login_uname1 = new javax.swing.JTextField();
        login_pass1 = new javax.swing.JPasswordField();
        cb11 = new javax.swing.JCheckBox();
        lbl41 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Loginn_pb1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logintimelbl = new javax.swing.JLabel();
        logindatelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        login_uname1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        login_uname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_uname1ActionPerformed(evt);
            }
        });
        login_uname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_uname1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                login_uname1KeyReleased(evt);
            }
        });
        getContentPane().add(login_uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 260, -1));

        login_pass1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        login_pass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_pass1ActionPerformed(evt);
            }
        });
        login_pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_pass1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                login_pass1KeyReleased(evt);
            }
        });
        getContentPane().add(login_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 260, -1));

        cb11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        cb11.setForeground(new java.awt.Color(255, 255, 255));
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        getContentPane().add(cb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 20, 20));

        lbl41.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl41, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 170, 20));

        lbl51.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl51, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 180, 20));

        jLabel3.setBackground(new java.awt.Color(230, 160, 40));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 170, 56));
        jLabel3.setText("*Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 170, 56));
        jLabel4.setText("*Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, 60));

        Loginn_pb1.setStringPainted(true);
        getContentPane().add(Loginn_pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 330, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Exit");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        logintimelbl.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        logintimelbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(logintimelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 20));

        logindatelbl.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        logindatelbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(logindatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multipleloginarraylist/welcomepic.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_uname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_uname1ActionPerformed

    private void login_uname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_uname1KeyPressed
        String un = login_uname1.getText();
        int uname_length = un.length();
        char a = evt.getKeyChar();

        if (Character.isLetter(a)) {

            if (uname_length < 10) {
                login_uname1.setEditable(true);
            } else {
                login_uname1.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(a) || Character.isISOControl(a) || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT || evt.getExtendedKeyCode() == KeyEvent.VK_2) {
                login_uname1.setEditable(true);
            } else {
                login_uname1.setEditable(false);
            }
        }
    }//GEN-LAST:event_login_uname1KeyPressed

    private void login_uname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_uname1KeyReleased
        lbl41.setText("");
    }//GEN-LAST:event_login_uname1KeyReleased

    private void login_pass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_pass1KeyPressed
        String pas = login_pass1.getText();
        int pass_length = pas.length();
        char b = evt.getKeyChar();

        if (Character.isDigit(b)) {

            if (pass_length < 10) {
                login_pass1.setEditable(true);
            } else {
                login_pass1.setEditable(false);
            }
        } else {
            if (Character.isISOControl(b)) {
                login_pass1.setEditable(true);
            } else {
                login_pass1.setEditable(false);
            }
        }
    }//GEN-LAST:event_login_pass1KeyPressed

    private void login_pass1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_pass1KeyReleased
        lbl51.setText("");
    }//GEN-LAST:event_login_pass1KeyReleased

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        if (cb11.isSelected()) {
            login_pass1.setEchoChar((char) 0);
            cb11.setText("Hide Password");
        } else {
            login_pass1.setEchoChar('*');
            cb11.setText("Show Password");
        }

    }//GEN-LAST:event_cb11ActionPerformed

    private void login_pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_pass1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String query,username=null,passdb=null;
        String uname1 = login_uname1.getText();
        String pass1 = login_pass1.getText();
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/hotelmanagementsystem";
        SUser = "root";
        SPass = "";
        int notFound=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            if("".equals(uname1)){
                JOptionPane.showMessageDialog(null, "Username is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(pass1)){
                JOptionPane.showMessageDialog(null, "Password is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else {
            
            query = "SELECT * FROM `user accounts` WHERE name = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, uname1);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                passdb = rs.getString("password");
                username = rs.getString("name");
                notFound = 1;
            }
            if(notFound == 1 && pass1.equals(passdb)){
                Dashboardd Dashboardd = new Dashboardd();
                Dashboardd.setVisible(true);
                Dashboardd.setLocationRelativeTo(null); 
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(null, "Incorrect email or password", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            login_pass1.setText("");
            
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*

        int a = MultipleLogin.username.size();
        int i;

        if (MultipleLogin.username.indexOf(uname1) >= 0) {
            for (i = 0; i < a;) {
                if (!uname1.equals(MultipleLogin.username.get(i))) {
                    i++;

                } else {
                    if (!pass1.equals(MultipleLogin.password.get(i))) {
                        attempt--;
                        JOptionPane.showMessageDialog(null, "Incorrect Password for " + uname1 + " account." + ", " + "Remaining attempts = " + attempt);
                        login_pass1.setText("");
                        break;
                    } else {    
                        tmr = new Timer(50, new Loginn.prog());
                        tmr.start();
                        Dashboardd.dboardacclbl.disable();
                        Dashboardd.userlogsanghistorylbl.disable();
                        Dashboardd.userlogsanghistorylbl.disable();
                        Dashboardd.jLabel48.setText(uname1);
                        String data1 = uname1;
                        String data2 = logindatelbl.getText();
                        String data3 = logintimelbl.getText();
                        Object[] userlogsrow = {data1, data2, data3};
                        DefaultTableModel model = (DefaultTableModel) Dashboardd.userlogtable.getModel();
                        model.addRow(userlogsrow);
        
                        MultipleLogin.logsuser.add(data1); MultipleLogin.logsuserdate.add(data2); MultipleLogin.logsuserdatetimein.add(data3);
                        break;
                    }
                }
            }
        } else if (uname1.isEmpty() && pass1.isEmpty()) {
            lbl41.setText("Username is Empty");
            lbl51.setText("Password is empty");

        } else if (uname1.isEmpty()) {
            lbl41.setText("Username is Empty");

        } else if (pass1.isEmpty()) {
            lbl51.setText("Password is Empty");

        } else if (!uname1.equals("Admin") && pass1.equals("00000")) {
            attempt--;
            JOptionPane.showMessageDialog(null, "Incorrect username for admin account." + ", " + "Remaining attempts = " + attempt);
            login_uname1.setText("");
        } else if (uname1.equals("Admin") && !pass1.equals("00000")) {
            attempt--;
            JOptionPane.showMessageDialog(null, "Incorrect password for admin account." + ", " + "Remaining attempts = " + attempt);
            login_pass1.setText("");
        }else if (uname1.equals("Admin") && pass1.equals("00000")) {
            tmr = new Timer(50, new Loginn.prog());
            tmr.start();
            Dashboardd.dboardacclbl.setEnabled(true);
            Dashboardd.userlogsanghistorylbl.setEnabled(true);
            Dashboardd.jLabel48.setText(uname1);
            String data1 = uname1;
            String data2 = logindatelbl.getText();
            String data3 = logintimelbl.getText();
            Object[] userlogsrow = {data1, data2, data3};
            DefaultTableModel model = (DefaultTableModel) Dashboardd.userlogtable.getModel();
            model.addRow(userlogsrow);
            MultipleLogin.logsuser.add(data1); MultipleLogin.logsuserdate.add(data2); MultipleLogin.logsuserdatetimein.add(data3);
        }else {
            JOptionPane.showMessageDialog(null, "Username doesn't exist! Please try again.");
            login_uname1.setText("");
            login_pass1.setText("");
        }*/
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Loginn().setVisible(true);
            }
        });
    }
    private Timer tmr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loginn_pb1;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl51;
    public static javax.swing.JPasswordField login_pass1;
    public static javax.swing.JTextField login_uname1;
    public static javax.swing.JLabel logindatelbl;
    public static javax.swing.JLabel logintimelbl;
    // End of variables declaration//GEN-END:variables
}
